$controlNames = @(
    'WindowFrame','WindowBorderOverlay','TitleBar','MinimizeButton','MaximizeButton','MaximizeGlyph','CloseButton','TxtAppTitle','TxtAppSubtitleAnimated','TxtAppSubtitleCaret','TxtAdminMode','TxtReady','SidebarColumn','PrimaryNavPanel','SidebarToggleButton','SidebarToggleGlyph','SidebarStatusPanel','SidebarAdminShield','SidebarReadyPanel','SidebarReadyDot',
    'NavHome','NavHomeText','NavHistory','NavHistoryText','NavDiagnostics','NavDiagnosticsText','NavPerformance','NavPerformanceText','NavGames','NavGamesText','NavApplications','NavApplicationsText','NavConnections','NavConnectionsText','NavNetwork','NavNetworkText','NavFirewall','NavFirewallText','NavDns','NavDnsText','NavCommands','NavCommandsIcon','NavCommandsText','NavDebloat','NavDebloatText','NavAdvanced','NavAdvancedText','NavThisPc','NavThisPcText','NavSettings','NavSettingsText','NavAbout','NavAboutText','HomePage','HistoryPage','DiagnosticsPage','PerformancePage','GamesPage','ApplicationsPage','ConnectionsPage','NetworkPage','CommandsPage','DebloatPage','AdvancedPage','FirewallPage','DnsPage','ThisPcPage','SettingsPage','AboutPage',
    'HomeTitle','HomeSubtitle','SourceBanner','SourceDot','SourceBannerTitle','SourceBannerHint','ClearSourceButton',
    'SourceTitle','SourceLabel','SourceUrlBox','SourcePlaceholder','TestSourceButton','SourcePersistence','ManualAddButton','ManualAddHint',
    'UpdateModeTitle','MergeModeRadio','ReplaceModeRadio','ModeMerge','ModeMergeHint','ModeReplace','ModeReplaceHint','AutomaticBackupCheck','AutomaticBackup',
    'AutomationTitle','DailyUpdateCheck','DailyUpdate','DailyUpdateHint','UpdateTimeLabel','UpdateTimeCombo','FlushDnsCheck',
    'StatusTitle','LastUpdateLabel','LastUpdateValue','NextRunLabel','NextRunValue','ManagedEntriesLabel','ManagedEntriesValue','TaskStatusLabel','TaskStatusValue',
    'ActionsTitle','UpdateNowButton','RestoreLatestButton','OpenHostsButton',
    'HistoryTitle','HistorySubtitle','BackupGrid','DateColumn','NameColumn','SizeColumn','BackupPreviewPanel','BackupPreviewTitle','BackupPreviewMeta','BackupPreviewScroll','BackupPreviewCustomScrollTrack','BackupPreviewCustomScrollThumb','BackupPreviewText','BackupPreviewCloseButton','BackupContextMenu','ModifyBackupMenuItem','DeleteBackupMenuItem','DetailBackupMenuItem','DeleteSelectedBackupButton','ClearHistoryButton','OpenBackupFolderButton','RefreshHistoryButton','RestoreSelectedButton',
    'DiagnosticsTitle','DiagnosticsSubtitle','DiagnosticsAdvancedTitle','BootDiagnosticsTitle','BootDiagnosticsHint','BootDiagnosticsStatus','BootDiagnosticsToggle','VerboseLogonTitle','VerboseLogonHint','VerboseLogonStatus','VerboseLogonToggle','SystemRestoreTitle','SystemRestoreHint','SystemRestoreStatus','CreateRestorePointButton','OpenSystemRestoreButton','OpenIntegrityLogFolderButton',
    'PerformanceTitle','PerformanceSubtitle','PerformanceWindowsTitle','PerformanceGamesTitle','PerformanceStateText','RefreshPerformanceButton','DefenderCpuTitle','DefenderCpuHint','DefenderCpuSlider','DefenderCpuValue','ApplyDefenderCpuButton','BingSearchTitle','BingSearchHint','BingSearchToggle','SponsoredAppsTitle','SponsoredAppsHint','SponsoredAppsToggle','SuggestionsTitle','SuggestionsHint','SuggestionsToggle','PowerModeTitle','PowerModeHint','PowerModeStatus','PowerEcoButton','PowerNormalButton','PowerHighButton','TransparencyTitle','TransparencyHint','TransparencyToggle','AnimationsTitle','AnimationsHint','AnimationsToggle','ShutdownAnimationTitle','ShutdownAnimationHint','ShutdownAnimationToggle','HomeGalleryTitle','HomeGalleryHint','HomeGalleryToggle','ClockSecondsTitle','ClockSecondsHint','ClockSecondsToggle','NotificationsTitle','NotificationsHint','NotificationsToggle','EndTaskTitle','EndTaskHint','EndTaskToggle','LegacyContextTitle','LegacyContextHint','LegacyContextToggle','LegacyExplorerTitle','LegacyExplorerHint','LegacyExplorerToggle','GameDvrTitle','GameDvrHint','GameDvrToggle','BackgroundThrottleTitle','BackgroundThrottleHint','BackgroundThrottleToggle','LatencyTitle','LatencyHint','LatencyToggle','GamingTasksTitle','GamingTasksHint','GamingTasksToggle','BackgroundServicesTitle','BackgroundServicesHint','BackgroundServicesToggle','TaskbarOptimizeTitle','TaskbarOptimizeHint','TaskbarOptimizeToggle','StartupOptimizeTitle','StartupOptimizeHint','StartupOptimizeToggle','PerformanceLogTitle','PerformanceOutputBox','ExportPerformanceLogButton','OpenPerformanceLogButton','OpenPerformanceLogFolderButton','ClearPerformanceLogButton',
    'ConnectionsTitle','ConnectionsSubtitle','LiveConnectionsTitle','LiveConnectionsHint','RefreshConnectionsButton','ConnectionsGrid','ConnectionsContextMenu','ConnectionOpenLocationMenuItem','ConnectionStopMenuItem','ConnectionFirewallMenuItem','ConnectionPingMenuItem','ConnectionAppColumn','ConnectionPidColumn','ConnectionRemoteColumn','ConnectionProtocolColumn','ConnectionStateColumn','ConnectionPathColumn','OpenConnectionLocationButton','StopConnectionProcessButton','ConnectionToFirewallButton','ActiveConnectionCardTitle','NetworkToggleTitle','NetworkToggleHint','NetworkEnableButton','NetworkDisableButton',
    'NetworkTitle','NetworkSubtitle','NetworkCommandsTitle','NetworkTargetBox','NetworkTargetPlaceholder','NetworkDiagnosticButton','TraceRouteButton','NetstatHint','NetstatButton','IpconfigHint','IpconfigButton','FlushDnsNowHint','FlushDnsNowButton','ReleaseIpHint','ReleaseIpButton','RenewIpHint','RenewIpButton','NetworkLogTitle','NetworkOutputBox','ExportNetworkLogButton','OpenNetworkLogButton','OpenNetworkLogFolderButton','ClearNetworkLogButton','OpenPortsTitle','OpenPortsHint','RefreshOpenPortsButton','OpenPortsGrid','OpenPortsContextMenu','OpenPortFirewallMenuItem','OpenPortProtocolColumn','OpenPortAddressColumn','OpenPortNumberColumn','OpenPortAppColumn','OpenPortPidColumn','OpenPortPathColumn','OpenPortToFirewallButton','ProxyTitle','ProxyHint','ProxyHostBox','ProxyPortBox','EnableProxyButton','DisableProxyButton','ResetProxyButton','ProxyStatusText','PingTitle','PingHint','PingTargetBox','PingTargetPlaceholder','PingButton','PingLogTitle','PingOutputBox','ExportPingLogButton','OpenPingLogButton','OpenPingLogFolderButton','ClearPingLogButton',
    'DebloatTitle','DebloatSubtitle','AppxManagerTitle','AppxManagerHint','AppxScanButton','AppxLegendRecommended','AppxLegendOptional','AppxLegendProtected','AppxLegendHidden','AppxHiddenFilterPanel','AppxFilterRecommendedCheck','AppxFilterOptionalCheck','AppxFilterProtectedCheck','AppxFilterHiddenCheck','AppxSelectRecommendedButton','AppxSelectOptionalButton','AppxSelectProtectedButton','AppxSelectHiddenButton','AppxClearSelectionButton','AppxGrid','AppxStatusColumn','AppxSelectColumn','AppxNameColumn','AppxDescriptionColumn','AppxStatusText','AppxRemoveUserDataCheck','AppxRemoveButton','AppxLogTitle','AppxLogPanel','AppxLogBox','AppxLogCustomScrollTrack','AppxLogCustomScrollThumb','ExportAppxLogButton','OpenAppxLogButton','OpenAppxLogFolderButton','AppxClearLogButton','DebloatCleanupTitle','CleanupLogTitle','CleanupOutputBox','ExportCleanupLogButton','OpenCleanupLogButton','OpenCleanupLogFolderButton','ClearCleanupLogButton',
    'AdvancedTitle','AdvancedSubtitle','AdvancedOneDriveTitle','AdvancedOneDriveHint','AdvancedOneDriveButton','AdvancedTelemetryTitle','AdvancedTelemetryHint','AdvancedTelemetryBlockLabel','AdvancedTelemetryBlockStatus','AdvancedTelemetryPushedButton','AdvancedTelemetryAggressiveButton','AdvancedTelemetryDisableHostsButton','AdvancedEdgeTitle','AdvancedEdgeHint','AdvancedEdgeButton','AdvancedAiTitle','AdvancedAiHint','AdvancedAiButton','AdvancedLogTitle','AdvancedLogPanel','AdvancedLogBox','AdvancedLogCustomScrollTrack','AdvancedLogCustomScrollThumb','ExportAdvancedLogButton','OpenAdvancedLogButton','OpenAdvancedLogFolderButton','AdvancedClearLogButton','AdvancedStatusText',
    'CommandsTitle','CommandsSubtitle','WindowsActionsCard','WindowsCommandsTitle','KillPowerShellTitle','KillPowerShellHint','KillPowerShellButton','ClearTempTitle','ClearTempHint','ClearTempButton','RestartExplorerTitle','RestartExplorerHint','RestartExplorerButton','LocalUserTitle','LocalUserHint','LocalUserNameLabel','LocalUserNameBox','LocalUserPasswordLabel','LocalUserPasswordBox','LocalUserAdminCheck','CreateLocalUserButton','DeleteLocalUserButton','SafeModeBootTitle','SafeModeBootHint','SafeModeBootButton','DeleteSafeModeBootButton','PowerOptionsTitle','PowerOptionsHint','ShutdownButton','RestartComputerButton','GodModeToolTitle','GodModeToolHint','GodModeButton','SystemConsolesCard','SystemConsolesTitle','ThisPcTaskManagerTitle','ThisPcTaskManagerHint','ThisPcTaskManagerButton','MsConfigTitle','MsConfigHint','MsConfigButton','ServicesTitle','ServicesHint','ServicesButton','GroupPolicyTitle','GroupPolicyHint','GroupPolicyButton','RegistryTitle','RegistryHint','RegeditButton','TaskSchedulerTitle','TaskSchedulerHint','TaskSchedulerButton','EventViewerTitle','EventViewerHint','EventViewerButton','WingetUpgradeTitle','WingetUpgradeHint','WingetUpgradeButton','IntegrityCard','IntegrityTitle','DismScanTitle','DismScanHint','DismScanButton','DismRepairTitle','DismRepairHint','DismRepairButton','SfcToolTitle','SfcToolHint','SfcScanButton','ChkdskTitle','ChkdskHint','ChkdskButton','DriveHealthTitle','DriveHealthHint','DriveHealthButton','PathRepairTitle','PathRepairHint','RepairPathButton','IntegrityLogTitle','IntegrityLogHint','IntegrityLogPanel','IntegrityOutputBox','ExportIntegrityLogButton','OpenIntegrityLogButton','OpenIntegrityLogFolderButton','ClearIntegrityLogButton','WindowsLogTitle','WindowsOutputBox','ExportWindowsLogButton','OpenWindowsLogButton','OpenWindowsLogFolderButton','ClearWindowsLogButton',
    'FirewallTitle','FirewallSubtitle','FirewallAddTitle','FirewallAddHint','FirewallProgramBox','BrowseFirewallProgramsButton','BrowseFirewallFolderButton','FirewallPendingPanel','FirewallPendingTitle','FirewallPendingGrid','FirewallPendingNameColumn','FirewallPendingPathColumn','RemovePendingFirewallButton','ClearPendingFirewallButton','FirewallInboundCheck','FirewallOutboundCheck','FirewallActionLabel','FirewallActionCombo','FirewallProfileLabel','FirewallProfileCombo','AddFirewallRulesButton','FirewallRulesTitle','FirewallGrid','FirewallContextMenu','DeleteFirewallMenuItem','FirewallNameColumn','FirewallPathColumn','FirewallDirectionColumn','FirewallActionColumn','FirewallProfileColumn','FirewallStatusColumn','DeleteFirewallRulesButton','EnableFirewallRulesButton','DisableFirewallRulesButton','OpenAdvancedFirewallButton','RefreshFirewallButton',
    'DnsTitle','DnsSubtitle','DnsAdapterTitle','DnsAdapterHint','DnsAdapterCombo','RefreshDnsAdaptersButton','CurrentDnsTitle','CurrentDnsValue','DnsPresetsTitle','DnsPresetsHint','DnsPresetCombo','DnsPresetIpv4Label','DnsPresetIpv4Value','DnsPresetIpv6Label','DnsPresetIpv6Value','ApplyDnsPresetButton','CustomDnsTitle','CustomDnsHint','DnsIpv4PrimaryLabel','DnsIpv4PrimaryBox','DnsIpv4SecondaryLabel','DnsIpv4SecondaryBox','DnsIpv6PrimaryLabel','DnsIpv6PrimaryBox','DnsIpv6SecondaryLabel','DnsIpv6SecondaryBox','ApplyCustomDnsButton','DnsActionsTitle','DnsActionsHint','DnsStatusText','ResetAutomaticDnsButton','TestDnsButton','FlushDnsPageButton',
    'ThisPcTitle','ThisPcSubtitle','ThisPcHeaderActions','CopySpecsButton','RefreshSpecsButton','PcOverviewCard','PcOverviewTitle','ComputerNameLabel','ComputerNameValue','RenameComputerButton','OperatingSystemLabel','OperatingSystemValue','BuildLabel','BuildValue','SystemTypeLabel','SystemTypeValue','UptimeLabel','UptimeValue','ProcessorCard','ProcessorTitle','ProcessorValue','ProcessorDetailsValue','MemoryCard','MemoryTitle','MemoryValue','MemoryDetailsValue','GraphicsCard','GraphicsTitle','GraphicsValue','GraphicsDetailsValue','MotherboardCard','MotherboardTitle','MotherboardModelValue','MotherboardManufacturerValue','MotherboardBiosValue','MotherboardValue','StorageCard','StorageTitle','StorageDisksPanel','StorageValue','NetworkInfoCard','NetworkInfoTitle','NetworkAdapterValue','NetworkDetailsValue','DisplayCard','DisplayTitle','DisplayEmptyText','DisplayContentPanel','DisplayPreviousButton','DisplayRoleText','DisplayCounterText','DisplayNextButton','DisplayMonitorName','DisplayConnectionLabel','DisplayConnectionValue','DisplayLabelColumn','DisplayResolutionLabel','DisplayResolutionControls','DisplayResolutionCombo','DisplayApplyResolutionButton','DisplayRefreshLabel','DisplayRefreshControls','DisplayRefreshCombo','DisplayApplyRefreshButton','DisplayScalingLabel','DisplayScalingControls','DisplayScalingCombo','DisplayApplyScalingButton','DisplayIndicatorsPanel',
    'SettingsTitle','SettingsSubtitle','LanguageLabel','LanguageHint','LanguageCombo','AppearanceTitle','AppearanceHint','ThemeLabel','ThemeHint','ThemeCombo','CreateThemeButton','ModifyThemeButton','DeleteThemeButton','TitlebarAnimationLabel','TitlebarAnimationHint','TitlebarAnimationToggle','AccentLabel','AccentHint','AccentColorBox','ChooseAccentButton','ResetAccentButton','CornerLabel','CornerHint','CornerCombo','UiScaleLabel','UiScaleHint','UiScaleCombo','ApplyUiScaleButton','DataFolderLabel','DataFolderHint','DataFolderValue','ChooseDataFolderButton','ResetDataFolderButton','OpenDataFolderButton',
    'GamesTitle','GamesSubtitle','GamesOpenDownloadsButton','GamesLaunchersTitle','GamesLaunchersPanel','GamesTweaksTitle','GamesTweaksPanel','GamesClearProgressButton','GamesProgressTitle','GamesProgressStatus','GamesProgressPercent','GamesProgressBar','GamesProgressDetails','GamesLogTitle','GamesLogBox','GamesExportLogButton','GamesOpenLogButton','GamesClearLogButton',
    'ApplicationsTitle','ApplicationsSubtitle','ApplicationsOpenDownloadsButton','ApplicationsAppsTitle','ApplicationsAppsLeftPanel','ApplicationsAppsRightPanel','ApplicationsManufacturersTitle','ApplicationsManufacturersLeftPanel','ApplicationsManufacturersRightPanel','ApplicationsMiscTitle','ApplicationsMiscPanel','ApplicationsClearProgressButton','ApplicationsProgressTitle','ApplicationsProgressStatus','ApplicationsProgressPercent','ApplicationsProgressBar','ApplicationsProgressDetails','ApplicationsLogTitle','ApplicationsLogBox','ApplicationsExportLogButton','ApplicationsOpenLogButton','ApplicationsClearLogButton',
    'AboutTitle','AboutSubtitle','AboutProfileCard','AboutProductCard','AboutSupportCard','AboutUpdateCard','AboutAvatar','AboutBio','AboutProductName','AboutDescription','AboutStarHint','AboutSupportTitle','GitHubProfileButton','GitHubButtonText','RepositoryButton','RepositoryButtonText','KoFiButton','KoFiButtonText','VersionText','UpdateCheckTitle','UpdateCheckStatus','CheckUpdatesButton','UpdateResultPanel','UpdateResultDot','UpdateResultText','UpdateResultAction','UpdateResultClose','StatusBarText','BusyProgress'
)
foreach ($name in $controlNames) { Set-Variable -Name $name -Value $window.FindName($name) -Scope Script }
if (-not $DateColumn) { $script:DateColumn = $BackupGrid.Columns[0] }
if (-not $NameColumn) { $script:NameColumn = $BackupGrid.Columns[1] }
if (-not $SizeColumn) { $script:SizeColumn = $BackupGrid.Columns[2] }
$script:BackupContextMenu = $BackupGrid.ContextMenu
$script:ModifyBackupMenuItem = $BackupContextMenu.Items[0]
$script:DeleteBackupMenuItem = $BackupContextMenu.Items[1]
$script:DetailBackupMenuItem = $BackupContextMenu.Items[2]
$script:FirewallContextMenu = $FirewallGrid.ContextMenu
$script:DeleteFirewallMenuItem = $FirewallContextMenu.Items[0]
$script:ConnectionsContextMenu = $ConnectionsGrid.ContextMenu
$script:ConnectionOpenLocationMenuItem = $ConnectionsContextMenu.Items[0]
$script:ConnectionStopMenuItem = $ConnectionsContextMenu.Items[1]
$script:ConnectionFirewallMenuItem = $ConnectionsContextMenu.Items[2]
$script:ConnectionPingMenuItem = $ConnectionsContextMenu.Items[3]
$script:OpenPortsContextMenu = $OpenPortsGrid.ContextMenu
$script:OpenPortFirewallMenuItem = $OpenPortsContextMenu.Items[0]

# Les éléments d'un ContextMenu WPF vivent dans un namescope séparé :
# Window.FindName() retourne donc $null. Les récupérer explicitement depuis
# AppxGrid.ContextMenu, comme pour les autres menus contextuels de WNST.
$script:AppxContextMenu = $AppxGrid.ContextMenu
$script:AppxOpenLocationMenuItem = $AppxContextMenu.Items[0]
$script:AppxDetailsMenuItem = $AppxContextMenu.Items[1]
$script:AppxStandaloneRemoveMenuItem = $AppxContextMenu.Items[2]
$script:AppxHideMenuItem = $AppxContextMenu.Items[3]

$DnsPresetCombo.ItemsSource = $script:DnsPresets
$DnsPresetCombo.SelectedIndex = 0
